---
- name:
  hosts: arista5
  gather_facts: True
  tasks:
    - debug: 
        var: ansible_facts

    - debug:
        msg: "{{ ansible_facts.net_all_ipv4_addresses }}"

    - debug: 
        var: ansible_network_os

    - debug:
        msg: "{{ ansible_host }}"