---
- name:
  hosts: nxos
  tasks:

   - name: Ensure interface set to routed mode (not idempotent)
      nxos_interfaces:
        config:
          - name: "{{ intf_name }}"
            enabled: True
            mode: layer3
        state: merged
        
   - nxos_l3_interfaces:
      config:
        - name: "{{ intf_name }}"
          ipv4:
            - address: "{{ ip_address }}/{{ netmask }}"
     state: merged

   - net_ping:
       dest: "{{ peer_ip }}" 
     register: output

   - name: Verify at least four ping responses received
      assert:
        that:
          - output.packets_rx >= 4         